## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
# Import promoter sequences
df1 = pd.read_csv("../input/promoter-nonpromotor-dna-sequences/PromoterSequence.txt",sep=">")
df1.drop(['EP 1 (+) mt:CoI_1; range -100 to 200.'],axis=1,inplace=True)
df1.dropna(subset = ['Unnamed: 0'],how='all',inplace=True)
df1.rename(columns={'Unnamed: 0':'sequence'},inplace=True)
df1.reset_index(inplace=True)
df1['label'] = 1
display(df1)

index                                           sequence  label
0          0  TTAATTTGTCCTTATTTGATTAAGAAGAATAAATCTTATATATAGA...      1
1          2  ATAGCTCAAATTGCTTTATTAGTATTAGAATCAGCTGTAGCTATAA...      1
2          4  AAGCTTCCCTTTAATGTGCTCCTTGTGAATACAGCATTACAATGCC...      1
3          6  TATGTAGAATCTGTACAAGTATCTGTGTTTGGACAATGGCATGTGT...      1
4          8  ACATATTACTGCATACAGGTCTCAAATTATAAAATGACACTCGTGG...      1
...      ...                                                ...    ...
11295  22590  CGACAAAGTTTGATCCATGTGCATTCTTGGCGCCTTATCGATAGCT...      1
11296  22592  CATATCTACATCTCGCTTGCTCCTTCCCTTTCGCTGCGTGTGTGTG...      1
11297  22594  ATACCGCGGAAGCGCAAAAGTACCAGAATTTCCCTGGTATCGCGCT...      1
11298  22596  ATTATTCCGAATTCTTTTATCAGATTTAAATATGGGAAACACTTTA...      1
11299  22598  AATTCATTTATACCTGCATTTGTAACTGTACTAAATCTTCAACCAA...      1

[11300 rows x 3 columns]

In [3]:
# Import non-promoter sequences
df2 = pd.read_csv('../input/promoter-nonpromotor-dna-sequences/NonPromoterSequence.txt',sep='>')
df2.drop(['EP 1 (+) mt:CoI_1; range -400 to -100.'],axis=1,inplace=True)
df2.dropna(subset = ['Unnamed: 0'],how='all',inplace=True)
df2.rename(columns={'Unnamed: 0':'sequence'},inplace=True)
df2.reset_index(inplace=True)
df2['label'] = 0
display(df2)

index                                           sequence  label
0          0  TAATTACATTATTTTTTTATTTACGAATTTGTTATTCCGCTTTTAT...      0
1          2  ATTTTTACAAGAACAAGACATTTAACTTTAACTTTATCTTTAGCTT...      0
2          4  AGAGATAGGTGGGTCTGTAACACTCGAATCAAAAACAATATTAAGA...      0
3          6  TATGTATATAGAGATAGGCGTTGCCAATAACTTTTGCGTTTTTTGC...      0
4          8  AGAAATAATAGCTAGAGCAAAAAACAGCTTAGAACGGCTGATGCTC...      0
...      ...                                                ...    ...
11295  22590  TGGTAAAAAATTGTACACCTAACTAGTGCCTTCATGTATACCACCA...      0
11296  22592  AGTGCAACTGGAGCCGTGCCGTGACCCACAGAGATCGCCCACTCGA...      0
11297  22594  GCATGGATTTCATATTATCTTAATCGACTTGCTTTTATAAAATAGG...      0
11298  22596  GTGACCAGGTTTTGCTCTAATGCGAAGTACGGATTGGGTAGAGATA...      0
11299  22598  TCATATTGAAAATTGATAAGATTGATATTAACGTAGCAAAGAAAGC...      0

[11300 rows x 3 columns]

In [4]:
df = pd.concat([df1,df2],axis=0)
df.drop(['index'],axis=1,inplace=True)
df

sequence  label
0      TTAATTTGTCCTTATTTGATTAAGAAGAATAAATCTTATATATAGA...      1
1      ATAGCTCAAATTGCTTTATTAGTATTAGAATCAGCTGTAGCTATAA...      1
2      AAGCTTCCCTTTAATGTGCTCCTTGTGAATACAGCATTACAATGCC...      1
3      TATGTAGAATCTGTACAAGTATCTGTGTTTGGACAATGGCATGTGT...      1
4      ACATATTACTGCATACAGGTCTCAAATTATAAAATGACACTCGTGG...      1
...                                                  ...    ...
11295  TGGTAAAAAATTGTACACCTAACTAGTGCCTTCATGTATACCACCA...      0
11296  AGTGCAACTGGAGCCGTGCCGTGACCCACAGAGATCGCCCACTCGA...      0
11297  GCATGGATTTCATATTATCTTAATCGACTTGCTTTTATAAAATAGG...      0
11298  GTGACCAGGTTTTGCTCTAATGCGAAGTACGGATTGGGTAGAGATA...      0
11299  TCATATTGAAAATTGATAAGATTGATATTAACGTAGCAAAGAAAGC...      0

[22600 rows x 2 columns]

In [5]:
for seq in df['sequence']:
    if 'N' in seq:
        display(df.loc[df['sequence']==seq])

sequence  label
1822  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGAATTC...      0

In [6]:
df.drop([1822],inplace=True)

In [7]:
for seq in df['sequence']:
    if 'N' in seq:
        display(df.loc[df['sequence']==seq])

In [8]:
sequences = list(df.loc[:,'sequence'])

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# The LabelEncoder encodes a sequence of bases as a sequence of integers: 0, 1, 2 and 3
integer_encoder = LabelEncoder()  
# The OneHotEncoder converts an array of integers to a sparse matrix where 
# each row corresponds to one possible value of each feature, i.e. only 01 and 1 are present in the matrix
one_hot_encoder = OneHotEncoder()   
input_features = []

for sequence in sequences:
  integer_encoded = integer_encoder.fit_transform(list(sequence))
  integer_encoded = np.array(integer_encoded).reshape(-1, 1)
  one_hot_encoded = one_hot_encoder.fit_transform(integer_encoded)
  input_features.append(one_hot_encoded.toarray())

    
np.set_printoptions(threshold=40)
#print(input_features.shape)
input_features = np.stack(input_features)
print("Example sequence\n-----------------------")
print('DNA Sequence #1:\n',sequences[0][:10],'...',sequence[0][-10:])
print('One hot encoding of Sequence #1:\n',input_features[0].T)

Example sequence
-----------------------
DNA Sequence #1:
 TTAATTTGTC ... T
One hot encoding of Sequence #1:
 [[0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 1. 1. 0.]]


In [10]:
labels = list(df.loc[:,'label'])
len(labels)

22598

In [11]:
one_hot_encoder = OneHotEncoder()
labels = np.array(labels).reshape(-1, 1)
input_labels = one_hot_encoder.fit_transform(labels).toarray()

print('Labels:\n',labels.T)
print('One-hot encoded labels:\n',input_labels.T)

Labels:
 [[1 1 1 ... 0 0 0]]
One-hot encoded labels:
 [[0. 0. 0. ... 1. 1. 1.]
 [1. 1. 1. ... 0. 0. 0.]]


In [12]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(
    input_features, input_labels, test_size=0.25, random_state=42,shuffle = True)

In [13]:
train_features.shape

(16948, 301, 4)

In [14]:
train_labels.shape

(16948, 2)

In [15]:
test_features.shape

(5650, 301, 4)

In [19]:
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv1D, MaxPooling1D,LSTM, GRU, Bidirectional
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [21]:
model = Sequential()
model.add(Conv1D(filters = 27,kernel_size=(4),activation='relu',input_shape=(301, 4)))
model.add(MaxPooling1D(pool_size=(3)))
model.add(Dropout(0.2))
model.add(Conv1D(filters=14,kernel_size=(2),activation = 'relu',padding='same'))
model.add(Bidirectional(GRU(128,activation='relu')))
model.add(Dropout(0.2))
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
# model.add(Dense(64,activation='relu'))
model.add(Dense(16,activation='relu',kernel_regularizer=regularizers.l2(0.01)))
model.add(Dense(2,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

2021-10-01 13:21:41.685849: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-10-01 13:21:41.689046: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib
2021-10-01 13:21:41.689082: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-01 13:21:41.689162: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5763da334db5): /proc/driver/nvidia/version does not exist
2021-10-01 13:21:41.690330: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operation

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 298, 27)           459       
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 99, 27)            0         
_________________________________________________________________
dropout (Dropout)            (None, 99, 27)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 99, 14)            770       
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               110592    
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               3

In [26]:
early_stop = tensorflow.keras.callbacks.EarlyStopping(monitor='val_accuracy',min_delta = 0.0005,patience=8,restore_best_weights = True)
history = model.fit(train_features,train_labels,batch_size=128,validation_data = (test_features,test_labels),epochs=100)

2021-10-01 13:31:13.216948: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-10-01 13:31:13.229501: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2199995000 Hz


Epoch 1/100
133/133 [==============================] - 44s 309ms/step - loss: 0.8539 - accuracy: 0.5930 - val_loss: 0.6023 - val_accuracy: 0.7434
Epoch 2/100
133/133 [==============================] - 41s 306ms/step - loss: 0.5897 - accuracy: 0.7380 - val_loss: 0.5647 - val_accuracy: 0.7281
Epoch 3/100
133/133 [==============================] - 41s 308ms/step - loss: 0.5629 - accuracy: 0.7323 - val_loss: 0.5085 - val_accuracy: 0.7602
Epoch 4/100
133/133 [==============================] - 41s 305ms/step - loss: 0.5271 - accuracy: 0.7448 - val_loss: 0.5133 - val_accuracy: 0.7536
Epoch 5/100
133/133 [==============================] - 40s 304ms/step - loss: 0.5114 - accuracy: 0.7503 - val_loss: 0.4949 - val_accuracy: 0.7639
Epoch 6/100
133/133 [==============================] - 41s 307ms/step - loss: 0.5028 - accuracy: 0.7586 - val_loss: 0.4830 - val_accuracy: 0.7699
Epoch 7/100
133/133 [==============================] - 41s 306ms/step - loss: 0.4988 - accuracy: 0.7633 - val_loss: 0.4777 -

In [27]:
_, train_acc = model.evaluate(train_features, train_labels, verbose=0)
_, test_acc = model.evaluate(test_features, test_labels, verbose=0)

In [28]:
train_acc

0.9447132349014282

In [29]:
test_acc

0.886725664138794